-- Rafsi authority follows storage: valsi = official, definitions = proposals.
-- Fixed baseline snapshot of vlazba 1.0.11's official gismu/cmavo tables.
-- Includes each official gismu's implicit four-letter rafsi (except brod), as
-- required by V169. Full gismu forms remain implicit terminal rafsi in vlazba.
-- Keeping the reference data here makes this a standalone SQL migration.
CREATE TEMP TABLE official_rafsi_baseline (word TEXT PRIMARY KEY, rafsi TEXT NOT NULL) ON COMMIT DROP;
INSERT INTO official_rafsi_baseline (word, rafsi) VALUES
('backi', 'back'),
('bacru', 'ba''u bacr'),
('badna', 'badn'),
('badri', 'badr dri'),
('bajra', 'baj bajr'),
('bakfu', 'baf bakf'),
('bakni', 'bak bakn'),
('bakri', 'bakr'),
('baktu', 'bakt'),
('balji', 'balj'),
('balni', 'baln'),
('balre', 'ba''e balr'),
('balvi', 'balv bav'),
('bambu', 'bamb'),
('bancu', 'bac banc'),
('bandu', 'bad band'),
('banfi', 'banf'),
('bangu', 'ban bang bau'),
('banli', 'ba''i bal banl'),
('banro', 'ba''o banr'),
('banxa', 'banx bax'),
('banzu', 'banz baz'),
('bapli', 'bai bap bapl'),
('barda', 'bard bra'),
('bargu', 'bag barg'),
('barja', 'barj'),
('barna', 'ba''a barn'),
('bartu', 'bar bart'),
('basfa', 'basf'),
('basna', 'basn'),
('basti', 'bas bast'),
('batci', 'bat batc'),
('batke', 'batk'),
('bavmi', 'bavm'),
('baxso', 'baxs'),
('bebna', 'beb bebn'),
('bekpi', 'bekp'),
('bemro', 'be''o bem bemr'),
('bende', 'be''e bed bend'),
('bengo', 'beg beng'),
('benji', 'be''i bej benj'),
('benre', 'benr'),
('benzo', 'benz'),
('bergu', 'berg'),
('bersa', 'be''a bers bes'),
('berti', 'ber bert'),
('besna', 'ben besn'),
('besto', 'best'),
('betfu', 'be''u bef betf'),
('betri', 'bet betr'),
('bevri', 'bei bev bevr'),
('bi', 'biv'),
('bi''i', 'biz'),
('bidju', 'bidj'),
('bifce', 'bic bifc'),
('bikla', 'bik bikl'),
('bilga', 'big bilg'),
('bilma', 'bi''a bilm'),
('bilni', 'bil biln'),
('bindo', 'bid bind'),
('binra', 'binr'),
('binxo', 'bi''o binx bix'),
('birje', 'birj'),
('birka', 'bir birk'),
('birti', 'birt bit'),
('bisli', 'bis bisl'),
('bitmu', 'bi''u bim bitm'),
('bitni', 'bitn'),
('blabi', 'blab lab'),
('blaci', 'blac'),
('blanu', 'bla blan'),
('bliku', 'bli blik'),
('bloti', 'blo blot lo''i lot'),
('bo', 'bor'),
('bolci', 'boi bol bolc'),
('bongu', 'bo''u bog bong'),
('boske', 'bosk'),
('botpi', 'bo''i bot botp'),
('boxfo', 'bo''o bof boxf'),
('boxna', 'bo''a bon boxn'),
('bradi', 'brad'),
('brano', 'bran'),
('bratu', 'brat'),
('brazo', 'braz raz'),
('bredi', 'bre bred red'),
('bridi', 'bri brid'),
('brife', 'bi''e bif brif'),
('briju', 'bij brij'),
('brito', 'brit rit'),
('brivo', 'briv'),
('broda', 'rod'),
('brode', 'bo''e'),
('brodi', ''),
('brodo', ''),
('brodu', ''),
('bruna', 'brun bu''a bun'),
('bu', 'bu''i bus'),
('bu''a', 'bul'),
('budjo', 'bu''o budj buj'),
('bukpu', 'bu''u buk bukp'),
('bumru', 'bum bumr'),
('bunda', 'bud bund'),
('bunre', 'bu''e bunr bur'),
('burcu', 'bru burc'),
('burna', 'burn'),
('ca''a', 'caz'),
('cabna', 'cab cabn'),
('cabra', 'ca''a cabr'),
('cacra', 'cacr'),
('cadga', 'cadg'),
('cadzu', 'cadz dzu'),
('cafne', 'caf cafn'),
('cagna', 'cagn'),
('cakla', 'cakl'),
('calku', 'cak calk'),
('calse', 'cals'),
('canci', 'canc'),
('cando', 'cad cand'),
('cange', 'cag cang'),
('canja', 'caj canj'),
('canko', 'ca''o cank'),
('canlu', 'ca''u cal canl'),
('canpa', 'canp cna'),
('canre', 'can canr'),
('canti', 'cant'),
('carce', 'carc'),
('carfu', 'carf'),
('carmi', 'cai cam carm'),
('carna', 'car carn'),
('cartu', 'cart cat'),
('carvi', 'carv cav'),
('casnu', 'casn snu'),
('catke', 'ca''e catk'),
('catlu', 'catl cta'),
('catni', 'ca''i catn'),
('catra', 'catr'),
('caxno', 'cax caxn'),
('ce', 'cec'),
('ce''i', 'cez'),
('ce''o', 'ce''o'),
('cecla', 'ce''a cecl cel'),
('cecmu', 'ce''u cecm cem'),
('cedra', 'cedr'),
('cenba', 'cenb cne'),
('censa', 'cens ces'),
('centi', 'cen cent'),
('cerda', 'ced cerd'),
('cerni', 'cer cern'),
('certu', 'cert cre'),
('cevni', 'cei cev cevn'),
('cfale', 'cfal'),
('cfari', 'cfa cfar'),
('cfika', 'cfik fi''a fik'),
('cfila', 'cfi cfil'),
('cfine', 'cfin'),
('cfipu', 'cfip fi''u'),
('ci', 'cib'),
('ciblu', 'blu cibl'),
('cicna', 'cicn'),
('cidja', 'cidj dja'),
('cidni', 'cid cidn'),
('cidro', 'cidr dro'),
('cifnu', 'cif cifn'),
('cigla', 'cig cigl'),
('cikna', 'cik cikn'),
('cikre', 'cikr'),
('ciksi', 'ciks cki'),
('cilce', 'cic cilc'),
('cilfu', 'cilf'),
('cilmo', 'cilm cim'),
('cilre', 'cilr cli'),
('cilta', 'cil cilt'),
('cimde', 'cimd'),
('cimni', 'cimn'),
('cinba', 'cinb'),
('cindu', 'cind'),
('cinfo', 'cinf'),
('cinje', 'cij cinj'),
('cinki', 'cink'),
('cinla', 'cinl'),
('cinmo', 'cinm cni'),
('cinri', 'ci''i cinr'),
('cinse', 'cin cins'),
('cinta', 'cint'),
('cinza', 'cinz'),
('cipni', 'cipn cpi'),
('cipra', 'cip cipr'),
('cirko', 'cirk cri'),
('cirla', 'cirl'),
('ciska', 'ci''a cisk'),
('cisma', 'cism'),
('cisni', 'cisn'),
('ciste', 'ci''e cist'),
('citka', 'citk cti'),
('citno', 'ci''o cit citn'),
('citri', 'cir citr'),
('citsi', 'cits'),
('civla', 'civ civl'),
('cizra', 'ciz cizr'),
('ckabu', 'ckab'),
('ckafi', 'ckaf kaf'),
('ckaji', 'ckaj kai'),
('ckana', 'cka ckan'),
('ckape', 'cap ckap'),
('ckasu', 'cas ckas'),
('ckeji', 'cke ckej kej'),
('ckiku', 'ckik kik'),
('ckilu', 'ci''u ckil'),
('ckini', 'ckin ki''i'),
('ckire', 'ckir kir'),
('ckule', 'ckul cu''e kul'),
('ckunu', 'ckun ku''u'),
('cladu', 'clad lau'),
('clani', 'cla clan'),
('claxu', 'cau clax'),
('cletu', 'clet'),
('clika', 'clik'),
('clinu', 'clin'),
('clira', 'clir lir'),
('clite', 'clit lit'),
('cliva', 'cliv li''a liv'),
('clupa', 'clup cup'),
('cmaci', 'cmac'),
('cmalu', 'cma cmal'),
('cmana', 'cman ma''a'),
('cmavo', 'cmav ma''o'),
('cmene', 'cme cmen me''e'),
('cmeta', 'cmet'),
('cmevo', 'cmev'),
('cmila', 'cmil mi''a'),
('cmima', 'cmi cmim mim'),
('cmoni', 'cmo cmon co''i'),
('cnano', 'cnan na''o'),
('cnebo', 'cneb ne''o neb'),
('cnemu', 'cnem ne''u nem'),
('cnici', 'cnic nic'),
('cnino', 'cnin ni''o nin'),
('cnisa', 'cnis nis'),
('cnita', 'cnit ni''a nit'),
('co', 'col'),
('co''a', 'co''a'),
('co''e', 'co''e com'),
('co''u', 'co''u'),
('cokcu', 'cko cokc'),
('condi', 'cno coi con cond'),
('conka', 'conk'),
('corci', 'corc'),
('cortu', 'cor cort cro'),
('cpacu', 'cpa cpac'),
('cpana', 'cpan'),
('cpare', 'cpar par'),
('cpedu', 'cpe cped'),
('cpina', 'cpin'),
('cradi', 'crad'),
('crane', 'cra cran'),
('creka', 'cek crek'),
('crepu', 'crep rep'),
('cribe', 'crib rib'),
('crida', 'crid rid'),
('crino', 'crin ri''o'),
('cripu', 'crip rip'),
('crisa', 'cis cris'),
('critu', 'crit'),
('ctaru', 'ctar'),
('ctebi', 'cteb teb'),
('cteki', 'ce''i ctek tek'),
('ctile', 'ctil'),
('ctino', 'ctin ti''o'),
('ctuca', 'ctu ctuc'),
('cukla', 'cuk cukl'),
('cukre', 'cukr'),
('cukta', 'cku cukt'),
('culno', 'clu culn'),
('cumki', 'cu''i cum cumk'),
('cumla', 'cul cuml'),
('cunmi', 'cunm'),
('cunso', 'cu''o cun cuns'),
('cuntu', 'cu''u cunt'),
('cupra', 'cupr pra'),
('curmi', 'cru curm'),
('curnu', 'cur curn'),
('curve', 'curv cuv'),
('cusku', 'cus cusk sku'),
('cusna', 'cusn'),
('cutci', 'cuc cutc'),
('cutne', 'cut cutn'),
('cuxna', 'cu''a cux cuxn'),
('da', 'dav dza'),
('da''a', 'daz'),
('dacru', 'dac dacr'),
('dacti', 'dact dai'),
('dadjo', 'dadj daj'),
('dakfu', 'dak dakf'),
('dakli', 'dakl'),
('damba', 'da''a dab damb'),
('damri', 'damr'),
('dandu', 'dad dand'),
('danfu', 'daf danf'),
('danlu', 'da''u dal danl'),
('danmo', 'dam danm'),
('danre', 'da''e danr'),
('dansu', 'dans'),
('danti', 'dan dant'),
('daplu', 'dapl plu'),
('dapma', 'dap dapm'),
('darca', 'darc'),
('dargu', 'dag darg'),
('darlu', 'darl dau'),
('darno', 'da''o dar darn'),
('darsi', 'dars'),
('darxi', 'da''i darx dax'),
('daski', 'dask'),
('dasni', 'das dasn'),
('daspo', 'dasp spo'),
('dasri', 'dasr sri'),
('datka', 'datk'),
('datni', 'datn'),
('datro', 'datr'),
('datru', 'datr'),
('decti', 'dec dect'),
('degji', 'deg degj'),
('dejni', 'dej dejn'),
('dekpu', 'dekp'),
('dekto', 'dek dekt'),
('delno', 'de''o del deln'),
('dembi', 'deb demb'),
('denci', 'de''i den denc'),
('denmi', 'dem denm'),
('denpa', 'de''a denp dep'),
('dertu', 'de''u der dert'),
('derxi', 'derx dre'),
('desku', 'des desk'),
('detri', 'det detr'),
('dicma', 'dicm'),
('dicra', 'dicr dir'),
('didni', 'didn'),
('digno', 'dign'),
('dikca', 'dic dikc'),
('diklo', 'dikl klo'),
('dikni', 'dik dikn'),
('dilcu', 'dilc'),
('dilma', 'dilm'),
('dilnu', 'dil diln'),
('dimna', 'dim dimn'),
('dindi', 'dind'),
('dinju', 'di''u dij dinj'),
('dinko', 'di''o dink'),
('dinso', 'dins'),
('dirba', 'dib dirb'),
('dirce', 'di''e dirc'),
('dirgo', 'dig dirg'),
('disko', 'disk'),
('ditcu', 'ditc'),
('divzi', 'divz'),
('dizlo', 'diz dizl dzi'),
('djacu', 'djac jac jau'),
('djedi', 'dei dje djed'),
('djica', 'dji djic'),
('djine', 'djin jin'),
('djuno', 'djun ju''o jun'),
('do', 'doi don'),
('donri', 'do''i donr dor'),
('dotco', 'do''o dot dotc'),
('draci', 'drac'),
('drani', 'dra dran'),
('drata', 'dat drat'),
('drudi', 'dru drud rud'),
('du', 'du''o dub'),
('du''u', 'dum'),
('dugri', 'dug dugr'),
('dukse', 'du''e duks dus'),
('dukti', 'dukt dut'),
('dunda', 'du''a dud dund'),
('dunja', 'duj dunj'),
('dunku', 'du''u duk dunk'),
('dunli', 'du''i dun dunl'),
('dunra', 'dunr dur'),
('dutso', 'duts'),
('dzena', 'dze dzen'),
('dzipo', 'dzip zi''o zip'),
('facki', 'fa''i fack fak'),
('fadni', 'fad fadn'),
('fagri', 'fag fagr'),
('falnu', 'faln fan'),
('famti', 'famt'),
('fancu', 'fanc'),
('fange', 'fang'),
('fanmo', 'fa''o fam fanm'),
('fanri', 'fanr'),
('fanta', 'fant'),
('fanva', 'fanv'),
('fanza', 'fanz faz'),
('fapro', 'fap fapr pro'),
('farka', 'fark'),
('farlu', 'fa''u fal farl'),
('farna', 'fa''a far farn'),
('farvi', 'farv fav'),
('fasnu', 'fasn fau'),
('fatci', 'fac fatc'),
('fatne', 'fa''e fat fatn'),
('fatri', 'fai fatr'),
('febvi', 'feb febv'),
('fegli', 'fegl'),
('femti', 'fem femt'),
('fendi', 'fed fend'),
('fengu', 'fe''u feg feng'),
('fenki', 'fek fenk'),
('fenra', 'fe''a fenr fer'),
('fenso', 'fe''o fen fens'),
('fepni', 'fei fep fepn'),
('fepri', 'fepr'),
('ferti', 'fert fre'),
('festi', 'fes fest'),
('fetsi', 'fe''i fet fets'),
('figre', 'fig figr'),
('filso', 'fils fis'),
('finpe', 'fi''e finp fip'),
('finti', 'fi''i fin fint'),
('firca', 'firc'),
('fisli', 'fisl'),
('fizbu', 'fizb'),
('flaci', 'flac'),
('flalu', 'fla flal'),
('flani', 'flan'),
('flecu', 'fle flec'),
('flese', 'fles'),
('fliba', 'fli flib'),
('flira', 'fir flir'),
('fo''a', 'fo''a'),
('fo''e', 'fo''e'),
('fo''i', 'fo''i'),
('foldi', 'flo foi fold'),
('fonmo', 'fo''o fom fonm'),
('fonxa', 'fon fonx'),
('forca', 'forc fro'),
('forse', 'fors'),
('fraso', 'fas fras'),
('frati', 'fra frat'),
('fraxu', 'fax frax'),
('frica', 'fic fric'),
('friko', 'fi''o frik'),
('frili', 'fil fril'),
('frinu', 'frin'),
('friti', 'fit frit'),
('frumu', 'fru frum'),
('fukpi', 'fu''i fuk fukp'),
('fulta', 'flu ful fult'),
('funca', 'fu''a fun func'),
('fusra', 'fur fusr'),
('fuzme', 'fu''e fuz fuzm'),
('gacri', 'gacr gai'),
('gadri', 'gad gadr'),
('galfi', 'ga''i gaf galf'),
('galtu', 'ga''u gal galt'),
('galxe', 'galx'),
('ganlo', 'ga''o ganl'),
('ganra', 'gan ganr'),
('ganse', 'ga''e gans gas'),
('ganti', 'gant'),
('ganxo', 'ganx gax'),
('ganzu', 'ganz gaz'),
('gapci', 'gac gapc'),
('gapru', 'gap gapr'),
('garna', 'gar garn'),
('gasnu', 'gasn gau'),
('gaspo', 'gasp'),
('gasta', 'gast gat'),
('genja', 'gej genj'),
('gento', 'ge''o gent get'),
('genxu', 'genx gex'),
('gerku', 'ge''u ger gerk'),
('gerna', 'ge''a gen gern'),
('gidva', 'gi''a gid gidv'),
('gigdo', 'gi''o gig gigd'),
('ginka', 'gik gink'),
('girzu', 'gir girz gri'),
('gismu', 'gi''u gim gism'),
('glare', 'gla glar'),
('gleki', 'gei gek glek'),
('gletu', 'gle glet let'),
('glico', 'gic gli glic'),
('glife', 'glif'),
('glosa', 'glos'),
('gluta', 'glu glut'),
('gocti', 'goc goct'),
('gomsi', 'goms'),
('gotro', 'got gotr'),
('gradu', 'grad rau'),
('grafu', 'graf'),
('grake', 'gra grak'),
('grana', 'ga''a gran'),
('grasu', 'gras ras'),
('grava', 'grav'),
('greku', 'grek rek'),
('grusi', 'grus rus'),
('grute', 'grut rut'),
('gubni', 'gub gubn'),
('gugde', 'gu''e gug gugd'),
('gugle', 'gugl'),
('gumri', 'gumr'),
('gundi', 'gud gund'),
('gunka', 'gu''a gun gunk'),
('gunma', 'gum gunm'),
('gunro', 'gu''o gunr gur'),
('gunse', 'guns'),
('gunta', 'gunt gut'),
('gurni', 'gru gurn'),
('guska', 'guk gusk'),
('gusni', 'gu''i gus gusn'),
('gusta', 'gust'),
('gutci', 'guc gutc'),
('gutra', 'gutr'),
('guzme', 'guz guzm zme'),
('ja', 'jav'),
('jabre', 'jabr'),
('jadni', 'ja''i jad jadn'),
('jai', 'jax'),
('jakne', 'jakn'),
('jalge', 'ja''e jag jalg'),
('jalna', 'jaln'),
('jalra', 'jalr'),
('jamfu', 'jaf jamf jma'),
('jamna', 'jam jamn'),
('janbe', 'jab janb'),
('janco', 'jan janc'),
('janli', 'jal janl'),
('jansu', 'jans jas'),
('janta', 'jant jat'),
('jarbu', 'jarb'),
('jarco', 'ja''o jarc'),
('jarki', 'jak jark'),
('jaspu', 'jap jasp'),
('jatna', 'ja''a jatn'),
('javni', 'javn jva'),
('jbama', 'bam jbam'),
('jbari', 'jba jbar'),
('jbena', 'jbe jben'),
('jbera', 'jber jer'),
('jbini', 'bi''i bin jbin'),
('jdari', 'jar jdar'),
('jdice', 'jdi jdic'),
('jdika', 'jdik'),
('jdima', 'di''a jdim'),
('jdini', 'di''i din jdin'),
('jduli', 'dul jdu jdul'),
('je', 'jev jve'),
('jecta', 'je''a jec ject'),
('jeftu', 'jef jeft'),
('jegvo', 'je''o jeg jegv'),
('jei', 'jez'),
('jelca', 'jel jelc'),
('jemna', 'jemn jme'),
('jenca', 'jen jenc'),
('jendu', 'jed jend'),
('jenmi', 'jei jem jenm'),
('jensi', 'jens'),
('jerna', 'jern'),
('jersi', 'je''i jers'),
('jerxo', 'jerx jex'),
('jesni', 'jes jesn'),
('jetce', 'je''e jetc'),
('jetnu', 'je''u jet jetn'),
('jgalu', 'ja''u jgal'),
('jganu', 'jga jgan'),
('jgari', 'jai jgar'),
('jgena', 'jge jgen'),
('jgina', 'gin jgin'),
('jgira', 'jgi jgir'),
('jgita', 'git jgit'),
('jibni', 'jbi jibn'),
('jibri', 'jib jibr'),
('jicla', 'jicl'),
('jicmu', 'cmu jicm'),
('jijnu', 'jij jijn'),
('jikca', 'jik jikc'),
('jikfi', 'jikf'),
('jikni', 'jikn'),
('jikru', 'jikr'),
('jilka', 'jil jilk'),
('jilra', 'jilr'),
('jimca', 'jic jimc'),
('jimpe', 'jimp jmi'),
('jimte', 'jimt jit'),
('jinci', 'jinc'),
('jinda', 'jind'),
('jinga', 'ji''a jig jing'),
('jinku', 'jink'),
('jinme', 'jim jinm'),
('jinru', 'jinr jir'),
('jinsa', 'jins jis'),
('jinto', 'jint'),
('jinvi', 'ji''i jinv jiv'),
('jinzi', 'jinz jiz'),
('jipci', 'jipc'),
('jipno', 'ji''o jip jipn'),
('jirna', 'jirn'),
('jisra', 'jisr'),
('jitfa', 'jif jitf'),
('jitro', 'jitr tro'),
('jivbu', 'jivb'),
('jivna', 'jivn jvi'),
('jmaji', 'jaj jmaj'),
('jmifa', 'jmif'),
('jmina', 'jmin min'),
('jmive', 'ji''e jmiv miv'),
('jo', 'jov'),
('jo''e', 'jom'),
('jo''u', 'jo''u'),
('joi', 'joi jol'),
('jonse', 'jons'),
('jordo', 'jo''o jor jord'),
('jorne', 'jo''e jon jorn'),
('ju', 'juv'),
('jubme', 'jbu jub jubm'),
('judri', 'judr'),
('jufra', 'ju''a juf jufr'),
('jukni', 'juk jukn'),
('jukpa', 'jukp jup'),
('julne', 'ju''e juln'),
('julro', 'julr'),
('jundi', 'ju''i jud jund'),
('jungo', 'jug jung'),
('junla', 'jul junl'),
('junri', 'junr jur'),
('junta', 'junt'),
('jurme', 'jum jurm'),
('jursa', 'jurs jus'),
('jutsi', 'jut juts'),
('juxre', 'jux juxr'),
('jvinu', 'ji''u jvin vin'),
('jviso', 'jvis'),
('ka', 'kam'),
('kabri', 'kabr'),
('kacma', 'kacm'),
('kadno', 'kadn'),
('kafke', 'kafk'),
('kagni', 'kag kagn'),
('kajde', 'jde kajd'),
('kajna', 'kajn'),
('kakne', 'ka''e kakn'),
('kakpa', 'kakp'),
('kalci', 'kalc'),
('kalri', 'kalr kar'),
('kalsa', 'kals kas'),
('kalte', 'kalt kat'),
('kamju', 'kamj'),
('kamni', 'kamn'),
('kampu', 'kamp kau'),
('kamre', 'kamr'),
('kanba', 'kanb'),
('kancu', 'kac kanc'),
('kandi', 'kad kand'),
('kanji', 'kaj kanj'),
('kanla', 'kal kanl'),
('kanpe', 'kanp'),
('kanro', 'ka''o kanr'),
('kansa', 'kan kans'),
('kantu', 'ka''u kant'),
('kanxe', 'kanx kax'),
('karbi', 'kab karb'),
('karce', 'karc'),
('karda', 'kard'),
('kargu', 'karg'),
('karli', 'karl'),
('karni', 'karn'),
('katci', 'katc'),
('katna', 'ka''a katn'),
('kavbu', 'kav kavb'),
('kazra', 'kazr'),
('ke', 'kem'),
('ke''e', 'ke''e kep'),
('kecti', 'ke''i kec kect'),
('kei', 'kez'),
('kekli', 'kekl'),
('kelci', 'kei kel kelc'),
('kelvo', 'ke''o kelv'),
('kenka', 'kenk'),
('kenra', 'ken kenr'),
('kensa', 'kens kes'),
('kerfa', 'kerf kre'),
('kerlo', 'ker kerl'),
('kesri', 'kesr'),
('ketco', 'ket ketc tco'),
('ketsu', 'kets'),
('kevna', 'ke''a kev kevn'),
('kicne', 'ki''e kic kicn'),
('kijno', 'kij kijn'),
('kilto', 'ki''o kilt'),
('kinda', 'kind'),
('kinli', 'kil kinl'),
('kisto', 'kis kist'),
('klaji', 'klaj laj'),
('klaku', 'kak klak'),
('klama', 'kla klam'),
('klani', 'klan lai'),
('klesi', 'kle kles lei'),
('kliki', 'klik'),
('klina', 'kli klin'),
('kliru', 'klir'),
('kliti', 'kit klit'),
('klupe', 'klup lu''e lup'),
('kluza', 'kluz luz'),
('kobli', 'ko''i kob kobl'),
('kogno', 'kogn'),
('kojna', 'ko''a koj kojn'),
('kokso', 'koks'),
('kolme', 'ko''e kol kolm'),
('komcu', 'kom komc'),
('konju', 'ko''u kon konj'),
('korbi', 'koi kor korb'),
('korcu', 'korc kro'),
('korka', 'kok kork'),
('korvo', 'korv'),
('kosmu', 'kosm'),
('kosta', 'kos kost'),
('krali', 'kral'),
('kramu', 'kram'),
('krasi', 'kra kras'),
('krati', 'ka''i krat'),
('krefu', 'ke''u kref ref'),
('krici', 'kri kric'),
('krili', 'kril'),
('krinu', 'ki''u krin rin'),
('krixa', 'ki''a kix krix'),
('kruca', 'kruc kuc'),
('kruji', 'kruj ruj'),
('kruvi', 'kru kruv ruv'),
('ku''a', 'kuz'),
('kubli', 'kub kubl'),
('kucli', 'kucl'),
('kufra', 'kuf kufr'),
('kukte', 'kuk kukt'),
('kulnu', 'klu kuln'),
('kumfa', 'ku''a kum kumf'),
('kumte', 'kumt'),
('kunra', 'kun kunr'),
('kunti', 'kunt kut'),
('kurfa', 'kur kurf'),
('kurji', 'ku''i kuj kurj'),
('kurki', 'kurk'),
('kuspe', 'ku''e kup kusp'),
('kusru', 'kus kusr'),
('labno', 'labn'),
('lacni', 'lacn'),
('lacpu', 'cpu lacp lap'),
('lacri', 'lac lacr'),
('ladru', 'lad ladr'),
('lafti', 'laf laft'),
('lakne', 'la''e lakn'),
('lakse', 'lak laks'),
('laldo', 'lald'),
('lalxu', 'la''u lalx'),
('lamji', 'la''i lam lamj'),
('lanbi', 'lanb'),
('lanci', 'lanc'),
('landa', 'land'),
('lanka', 'lank'),
('lanli', 'lal lanl'),
('lanme', 'lan lanm'),
('lante', 'lant'),
('lanxe', 'lanx lax'),
('lanzu', 'lanz laz'),
('larcu', 'lar larc'),
('larva', 'larv'),
('lasna', 'la''a lasn'),
('lastu', 'last'),
('latmo', 'la''o latm'),
('latna', 'latn'),
('lazni', 'lazn'),
('le''e', 'lem'),
('lebna', 'le''a leb lebn'),
('lelxe', 'lelx'),
('lenga', 'leng'),
('lenjo', 'le''o len lenj'),
('lenku', 'lek lenk'),
('lerci', 'lec lerc'),
('lerfu', 'le''u ler lerf'),
('li''i', 'liz'),
('libjo', 'lib libj'),
('lidne', 'li''e lidn'),
('lifri', 'fri lif lifr'),
('lijda', 'jda lijd'),
('limfa', 'limf'),
('limna', 'lim limn'),
('lince', 'linc'),
('lindi', 'lid lind'),
('linga', 'ling'),
('linji', 'li''i lij linj'),
('linsi', 'lin lins'),
('linto', 'li''o lint'),
('lisri', 'lis lisr'),
('liste', 'list ste'),
('litce', 'lic litc'),
('litki', 'lik litk'),
('litru', 'li''u litr'),
('livga', 'livg'),
('livla', 'lil livl'),
('lo''e', 'lom'),
('logji', 'logj loj'),
('loglo', 'logl'),
('lojbo', 'jbo lob lojb'),
('loldi', 'loi lol lold'),
('lorxu', 'lo''u lor lorx'),
('lubno', 'lu''o lubn'),
('lujvo', 'jvo lujv luv'),
('luksi', 'luks'),
('lumci', 'lu''i lum lumc'),
('lunbe', 'lub lunb'),
('lunra', 'lunr lur'),
('lunsa', 'luns lus'),
('luska', 'lusk'),
('lusto', 'lust'),
('mabla', 'mabl mal'),
('mabru', 'mab mabr'),
('macnu', 'cnu macn'),
('majga', 'majg'),
('makcu', 'ma''u makc'),
('makfa', 'maf makf'),
('maksi', 'mak maks'),
('malsi', 'mals mas'),
('mamta', 'mam mamt'),
('manci', 'mac manc'),
('manfo', 'manf'),
('mango', 'mang'),
('manku', 'man mank'),
('manri', 'manr mar'),
('mansa', 'mans'),
('manti', 'mant'),
('mapku', 'map mapk'),
('mapni', 'mapn'),
('mapra', 'mapr'),
('mapti', 'mapt mat'),
('marbi', 'marb mra'),
('marce', 'ma''e marc'),
('marde', 'mad mard'),
('margu', 'mag marg'),
('marji', 'mai maj marj'),
('marna', 'marn'),
('marxa', 'marx max'),
('masno', 'masn sno'),
('masti', 'ma''i mast'),
('matci', 'matc'),
('matli', 'matl'),
('matne', 'matn'),
('matra', 'matr'),
('mavji', 'mav mavj'),
('maxri', 'maxr xri'),
('mebri', 'meb mebr'),
('megdo', 'meg megd'),
('mei', 'mei mem'),
('mekso', 'me''o mek meks'),
('melbi', 'mel melb mle'),
('meljo', 'mej melj'),
('melmi', 'melm'),
('menli', 'men menl'),
('menre', 'menr'),
('mensi', 'me''i mens mes'),
('mentu', 'me''u ment met'),
('merko', 'mer merk'),
('merli', 'merl mre'),
('metfo', 'metf'),
('mexno', 'mex mexn'),
('mi', 'mib'),
('midju', 'midj mij'),
('mifra', 'mif mifr'),
('mikce', 'mic mikc'),
('mikri', 'mik mikr'),
('milti', 'mil milt'),
('milxe', 'milx mli'),
('minde', 'mi''e mid mind'),
('minji', 'mi''i minj'),
('minli', 'minl'),
('minra', 'minr mir'),
('mintu', 'mi''u mint mit'),
('mipri', 'mip mipr'),
('mirli', 'mirl'),
('misno', 'mi''o mis misn'),
('misro', 'misr'),
('mitre', 'mitr tre'),
('mixre', 'mix mixr xre'),
('mlana', 'mla mlan'),
('mlatu', 'lat mlat'),
('mleca', 'me''a mec mlec'),
('mledi', 'led mled'),
('mluni', 'lun mlun'),
('mo''a', 'mob'),
('mo''i', 'mov'),
('mogle', 'mogl'),
('moi', 'moi mom'),
('mokca', 'moc mokc'),
('moklu', 'mo''u mokl mol'),
('molki', 'mlo molk'),
('molro', 'mo''o molr'),
('morji', 'mo''i moj morj'),
('morko', 'mor mork'),
('morna', 'mo''a mon morn'),
('morsi', 'mors mro'),
('mosra', 'mos mosr'),
('mraji', 'mraj'),
('mrilu', 'mri mril'),
('mruli', 'mru mrul'),
('mu', 'mum'),
('mu''e', 'muf'),
('mucti', 'muct mut'),
('mudri', 'mud mudr'),
('mugle', 'mugl'),
('mukti', 'mu''i muk mukt'),
('mulno', 'mu''o mul muln'),
('munje', 'mu''e muj munj'),
('mupli', 'mup mupl'),
('murse', 'murs'),
('murta', 'mu''a mur murt'),
('muslo', 'mus musl'),
('mutce', 'mutc tce'),
('muvdu', 'mu''u muv muvd'),
('muzga', 'muz muzg'),
('na', 'nar'),
('na''e', 'nal'),
('nabmi', 'nabm nam'),
('nakni', 'nak nakn'),
('nalci', 'na''i nalc'),
('namcu', 'na''u nac namc'),
('nanba', 'nab nanb'),
('nanca', 'na''a nanc'),
('nandu', 'nad nand'),
('nanla', 'nanl'),
('nanmu', 'nanm nau'),
('nanvi', 'nanv nav'),
('narge', 'nag narg'),
('narju', 'naj narj'),
('natfe', 'na''e naf natf'),
('natmi', 'nai nat natm'),
('natsi', 'nats'),
('navni', 'navn'),
('naxle', 'nax naxl xle'),
('nazbi', 'naz nazb zbi'),
('nejni', 'nejn nen'),
('nelci', 'nei nel nelc'),
('nenri', 'ne''i nenr ner'),
('nerde', 'nerd'),
('ni', 'nil'),
('nibli', 'ni''i nib nibl'),
('nicfa', 'nicf'),
('nicte', 'cte nict'),
('nikle', 'nik nikl'),
('nilce', 'ni''e nilc'),
('nimre', 'nimr'),
('ninja', 'ninj'),
('ninmu', 'ni''u nim ninm'),
('nirna', 'nir nirn'),
('nitcu', 'nitc tcu'),
('nivji', 'niv nivj'),
('nixli', 'nix nixl xli'),
('no', 'non'),
('no''e', 'no''e nor'),
('nobli', 'no''i nobl nol'),
('norgo', 'norg'),
('notci', 'noi not notc'),
('nu', 'nun'),
('nu''o', 'nu''o'),
('nudle', 'nudl'),
('nukni', 'nuk nukn'),
('nunmu', 'nunm'),
('nupre', 'nu''e nup nupr'),
('nurma', 'num nurm'),
('nusna', 'nusn'),
('nutka', 'nutk'),
('nutli', 'nu''i nul nutl'),
('nuzba', 'nuz nuzb'),
('nuzlo', 'nuzl'),
('pa', 'pav'),
('pacna', 'pa''a pacn'),
('pagbu', 'pag pagb pau'),
('pagre', 'gre pagr'),
('pajni', 'pai pajn'),
('palci', 'pac palc'),
('palku', 'pak palk'),
('palma', 'palm'),
('palne', 'paln'),
('palpi', 'palp'),
('palta', 'palt'),
('pambe', 'pamb'),
('pamga', 'pamg'),
('panci', 'pan panc'),
('pandi', 'pad pand'),
('panje', 'panj'),
('panka', 'pank'),
('panlo', 'pa''o panl'),
('panpi', 'panp pap'),
('panra', 'panr'),
('pante', 'pant pat'),
('panzi', 'panz paz'),
('papri', 'papr'),
('parbi', 'pab parb'),
('pardu', 'pard'),
('parji', 'parj'),
('pastu', 'pas past'),
('patfu', 'pa''u paf patf'),
('patlu', 'patl'),
('patxu', 'patx pax'),
('paznu', 'pazn'),
('pe''a', 'pev'),
('pelji', 'pelj ple'),
('pelxu', 'pel pelx'),
('pemci', 'pem pemc'),
('penbi', 'peb penb'),
('pencu', 'pe''u pec penc'),
('pendo', 'pe''o ped pend'),
('penmi', 'pe''i pen penm'),
('pensi', 'pei pens pes'),
('pentu', 'pent'),
('perli', 'per perl'),
('pesxu', 'pesx pex'),
('petso', 'pet pets'),
('pevna', 'pevn'),
('pezli', 'pez pezl'),
('pi', 'piz'),
('pi''u', 'piv'),
('picti', 'pic pict'),
('pijne', 'pijn'),
('pikci', 'pikc'),
('pikta', 'pikt'),
('pilda', 'pild'),
('pilji', 'pi''i pilj'),
('pilka', 'pi''a pil pilk'),
('pilno', 'piln pli'),
('pimlu', 'pi''u pim piml'),
('pinca', 'pinc'),
('pindi', 'pid pind'),
('pinfu', 'pif pinf'),
('pinji', 'pinj'),
('pinka', 'pik pink'),
('pinsi', 'pins pis'),
('pinta', 'pin pint'),
('pinxe', 'pinx pix'),
('pipno', 'pi''o pipn'),
('pixra', 'pir pixr xra'),
('plana', 'plan'),
('platu', 'pla plat'),
('pleji', 'le''i lej plej'),
('plibu', 'pib plib'),
('plini', 'plin'),
('plipe', 'pi''e pip plip'),
('plise', 'plis'),
('plita', 'pit plit'),
('plixa', 'lix plix'),
('pluja', 'luj pluj'),
('pluka', 'pluk pu''a puk'),
('pluta', 'lu''a lut plut'),
('pocli', 'pocl'),
('polje', 'plo polj'),
('polno', 'pol poln'),
('ponjo', 'po''o pon ponj'),
('ponse', 'po''e pons pos'),
('poplu', 'popl'),
('porpi', 'po''i pop porp'),
('porsi', 'poi por pors'),
('porto', 'port pot'),
('prali', 'pal pral'),
('prami', 'pa''i pam pram'),
('prane', 'pa''e pran'),
('preja', 'pe''a pej prej'),
('prenu', 'pre pren'),
('preri', 'prer'),
('preti', 'pret rei ret'),
('prije', 'pij prij'),
('prina', 'pri prin'),
('pritu', 'prit'),
('proga', 'prog'),
('prosa', 'pros ro''a ros'),
('pruce', 'pruc ru''e ruc'),
('pruni', 'prun pun'),
('pruri', 'prur'),
('pruxi', 'prux ru''i rux'),
('pu''i', 'pus'),
('pu''u', 'puv'),
('pulce', 'pu''e puc pulc'),
('pulji', 'pulj'),
('pulni', 'puln'),
('punji', 'pu''i puj punj'),
('punli', 'pul punl'),
('pupsu', 'pups'),
('purci', 'pru pur purc'),
('purdi', 'pud purd'),
('purmo', 'pu''o pum purm'),
('racli', 'racl'),
('ractu', 'ract'),
('radno', 'ra''o radn'),
('rafsi', 'raf rafs'),
('ragbi', 'ragb'),
('ragve', 'ragv rav'),
('rakle', 'rakl'),
('rakso', 'raks'),
('raktu', 'ra''u rakt'),
('ralci', 'rac ralc'),
('ralju', 'ral ralj'),
('ralte', 'ra''e ralt'),
('randa', 'rad rand'),
('rango', 'rag rang'),
('ranji', 'ra''i ranj'),
('ranmi', 'ram ranm'),
('ransu', 'rans'),
('ranti', 'ran rant'),
('ranxi', 'ranx rax'),
('rapli', 'rap rapl'),
('rarna', 'rar rarn'),
('ratcu', 'ratc'),
('ratni', 'rat ratn'),
('re', 'rel'),
('rebla', 'reb rebl'),
('rectu', 're''u rec rect'),
('rekto', 'rekt'),
('remna', 're''a rem remn'),
('renro', 're''o renr rer'),
('renvi', 're''i renv rev'),
('respa', 'res resp'),
('rexsa', 'rexs'),
('ricfu', 'cfu ricf rif'),
('rigni', 'rig rign'),
('rijno', 'rij rijn'),
('rilti', 'ril rilt'),
('rimni', 'rim rimn'),
('rinci', 'rinc'),
('rindo', 'rind'),
('rinju', 'ri''u rinj'),
('rinka', 'ri''a rik rink'),
('rinsa', 'rins'),
('rirci', 'rirc'),
('rirni', 'rir rirn'),
('rirxe', 'ri''e rirx'),
('rismi', 'ris rism'),
('risna', 'risn'),
('ritli', 'ri''i ritl'),
('rivbi', 'riv rivb'),
('ro', 'rol'),
('roi', 'roi rom'),
('rokci', 'ro''i rok rokc'),
('romge', 'rog romg'),
('romlo', 'roml'),
('ronte', 'ront'),
('ropno', 'ro''o ron ropn'),
('rorci', 'ror rorc'),
('rotsu', 'ro''u rot rots tsu'),
('rozgu', 'roz rozg zgu'),
('ruble', 'ble rub rubl'),
('rufsu', 'ruf rufs'),
('runme', 'rum runm'),
('runta', 'runt'),
('rupnu', 'ru''u rup rupn'),
('rusko', 'ru''o ruk rusk'),
('rutni', 'run rutn'),
('sabji', 'sab sabj'),
('sabnu', 'sabn'),
('sacki', 'sack'),
('saclu', 'sacl'),
('sadjo', 'djo sadj'),
('sakci', 'sak sakc'),
('sakli', 'sakl sal'),
('sakta', 'sakt sat'),
('salci', 'salc sla'),
('salpo', 'sa''o salp'),
('salri', 'salr'),
('salta', 'salt'),
('samcu', 'samc'),
('sampu', 'samp sap'),
('sanbu', 'sanb'),
('sance', 'sanc sna'),
('sanga', 'sa''a sag sang'),
('sanji', 'saj sanj'),
('sanli', 'sa''i sanl'),
('sanmi', 'sai sanm'),
('sanso', 'sans'),
('santa', 'sant'),
('sarcu', 'sa''u sarc'),
('sarji', 'sarj sra'),
('sarlu', 'sarl'),
('sarni', 'sarn'),
('sarxe', 'sarx sax'),
('saske', 'sask ske'),
('satci', 'satc'),
('satre', 'sa''e satr'),
('savru', 'sav savr vru'),
('sazri', 'saz sazr'),
('se', 'sel'),
('sefsi', 'sefs'),
('sefta', 'seft sfe'),
('sekre', 'sekr'),
('selci', 'selc sle'),
('selfu', 'se''u sef self'),
('semto', 'semt sme'),
('senci', 'sec senc'),
('sengi', 'seng'),
('senpi', 'sen senp'),
('senta', 'sent set'),
('senva', 'senv sev sne'),
('sepli', 'sei sep sepl'),
('serti', 'ser sert'),
('sesre', 'sesr'),
('setca', 'se''a setc'),
('sevzi', 'se''i sevz sez'),
('sfani', 'sfan'),
('sfasa', 'sfa sfas'),
('sfofa', 'sfo sfof'),
('sfubu', 'sfub su''u sub'),
('si''o', 'siz'),
('sibli', 'sibl'),
('siclu', 'sicl sil'),
('sicni', 'si''i sicn'),
('sicpi', 'sicp'),
('sidbo', 'si''o sib sidb'),
('sidju', 'dju sidj'),
('sigja', 'sig sigj'),
('sigma', 'sigm'),
('sikta', 'sikt'),
('silka', 'sik silk'),
('silna', 'siln'),
('simlu', 'mlu siml'),
('simsa', 'sims smi'),
('simxu', 'si''u sim simx'),
('since', 'sinc'),
('sinma', 'si''a sinm'),
('sinso', 'sins'),
('sinxa', 'sinx sni'),
('sipna', 'sip sipn'),
('sirji', 'sir sirj'),
('sirxo', 'sirx six'),
('sisku', 'sis sisk'),
('sisti', 'sist sti'),
('sitna', 'sit sitn'),
('sivni', 'siv sivn'),
('skaci', 'skac'),
('skami', 'sam skam'),
('skapi', 'kap skap'),
('skari', 'ska skar'),
('skicu', 'ski skic'),
('skiji', 'sij skij'),
('skina', 'kin skin'),
('skori', 'sko skor'),
('skoto', 'ko''o kot skot'),
('skuba', 'skub'),
('skuro', 'ku''o skur'),
('slabu', 'sau slab'),
('slaka', 'slak'),
('slami', 'slam'),
('slanu', 'slan'),
('slari', 'sar slar'),
('slasi', 'las slas'),
('sligu', 'lig slig'),
('slilu', 'sli slil'),
('sliri', 'slir'),
('slovo', 'lo''o lov slov'),
('sluji', 'slu sluj'),
('sluni', 'slun'),
('smacu', 'smac'),
('smadi', 'smad'),
('smaji', 'sma smaj'),
('smaka', 'smak'),
('smani', 'sman'),
('smela', 'smel'),
('smoka', 'smo smok'),
('smuci', 'muc smuc'),
('smuni', 'mun smu smun'),
('smusu', 'smus'),
('snada', 'sad snad'),
('snanu', 'nan snan'),
('snidu', 'nid snid'),
('snime', 'si''e snim'),
('snipa', 'nip snip'),
('snuji', 'nuj snuj'),
('snura', 'nu''a nur snur'),
('snuti', 'nut snut'),
('so', 'soz'),
('so''a', 'soj'),
('so''e', 'sop'),
('so''i', 'so''i sor'),
('so''o', 'sos'),
('so''u', 'sot'),
('sobde', 'so''e sob sobd'),
('sodna', 'sodn'),
('sodva', 'sod sodv'),
('softo', 'sof soft'),
('solji', 'slo solj'),
('solri', 'sol solr'),
('sombo', 'so''o som somb'),
('sonci', 'soi son sonc'),
('sorcu', 'soc sorc sro'),
('sorgu', 'sog sorg'),
('sorni', 'sorn'),
('sorta', 'sort'),
('sovda', 'so''a sov sovd'),
('spaji', 'paj spaj'),
('spali', 'spal'),
('spano', 'san span'),
('spati', 'spa spat'),
('speni', 'spe spen'),
('spero', 'sper'),
('spisa', 'spi spis'),
('spita', 'spit'),
('spofu', 'po''u pof spof'),
('spoja', 'po''a poj spoj'),
('spuda', 'spu spud'),
('sputu', 'pu''u put sput'),
('sraji', 'raj sraj'),
('sraku', 'rak srak'),
('sralo', 'sral'),
('srana', 'ra''a sran'),
('srasu', 'sas sras'),
('srera', 'sre srer'),
('srito', 'srit'),
('sruma', 'ru''a srum'),
('sruri', 'rur sru srur'),
('stace', 'sac stac'),
('stagi', 'stag'),
('staku', 'stak tak'),
('stali', 'sta stal'),
('stani', 'stan'),
('stapa', 'stap tap'),
('stasu', 'stas'),
('stati', 'stat'),
('steba', 'seb steb'),
('steci', 'stec te''i tec'),
('stedu', 'sed sted'),
('stela', 'stel tel'),
('stero', 'ster te''o'),
('stici', 'sic stic'),
('stidi', 'sid stid ti''i'),
('stika', 'stik tik'),
('stizu', 'stiz tiz'),
('stodi', 'sto stod'),
('stuna', 'stun sun'),
('stura', 'stur su''a tur'),
('stuzi', 'stu stuz tuz'),
('su''e', 'su''e sup'),
('su''o', 'su''o suz'),
('su''u', 'suv'),
('sucta', 'suc suct'),
('sudga', 'sud sudg'),
('sufti', 'sfu suft'),
('suksa', 'suk suks'),
('sumji', 'suj sumj'),
('sumne', 'sumn'),
('sumti', 'su''i sum sumt'),
('sunga', 'sug sung'),
('sunla', 'sul sunl'),
('surla', 'sur surl'),
('sutra', 'sut sutr'),
('ta', 'taz'),
('tabno', 'tab tabn'),
('tabra', 'tabr'),
('tadji', 'tadj'),
('tadni', 'tad tadn'),
('tagji', 'tag tagj'),
('taksi', 'taks'),
('talsa', 'tal tals'),
('tamca', 'tamc'),
('tamji', 'taj tamj'),
('tamne', 'tamn'),
('tanbo', 'ta''o tanb'),
('tance', 'tac tanc'),
('tanjo', 'tanj'),
('tanko', 'tank'),
('tanru', 'tanr tau'),
('tansi', 'tans tas'),
('tanxe', 'ta''e tanx tax'),
('tapla', 'tapl'),
('tarbi', 'tarb'),
('tarci', 'tar tarc'),
('tarla', 'tarl'),
('tarmi', 'tai tam tarm'),
('tarti', 'tart tra'),
('taske', 'task'),
('tasmi', 'tasm'),
('tasta', 'tast'),
('tatpi', 'ta''i tatp'),
('tatru', 'tat tatr'),
('tavla', 'ta''a tav tavl'),
('taxfu', 'ta''u taf taxf'),
('tcaci', 'cac tcac'),
('tcadu', 'tca tcad'),
('tcana', 'tcan'),
('tcati', 'tcat'),
('tcaxe', 'tcax'),
('tcena', 'tcen ten'),
('tcese', 'tces'),
('tcica', 'tcic tic'),
('tcidu', 'tcid tid'),
('tcika', 'tcik'),
('tcila', 'tcil til'),
('tcima', 'tcim ti''a tim'),
('tcini', 'tcin'),
('tcita', 'tcit'),
('te', 'ter'),
('temci', 'tei tem temc'),
('temse', 'tems'),
('tende', 'tend'),
('tenfa', 'tef tenf'),
('tengu', 'te''u teg teng'),
('terdi', 'ted terd'),
('terpa', 'te''a tep terp'),
('terto', 'tert tet'),
('ti', 'tif'),
('tifri', 'tifr'),
('tigni', 'tig tign'),
('tigra', 'tigr'),
('tikpa', 'tikp tip'),
('tilju', 'tij tilj'),
('tinbe', 'tib tinb'),
('tinci', 'tinc'),
('tinsa', 'tins'),
('tirna', 'tin tirn'),
('tirse', 'tir tirs'),
('tirxu', 'tirx'),
('tisna', 'tis tisn'),
('titla', 'tit titl'),
('tivni', 'tiv tivn'),
('tixnu', 'ti''u tix tixn'),
('to''e', 'to''e tol'),
('toknu', 'tok tokn'),
('toldi', 'tod told'),
('tonga', 'to''a tog tong'),
('tordu', 'to''u tor tord'),
('torni', 'to''i ton torn'),
('torso', 'tors'),
('traji', 'rai traj'),
('trano', 'tran'),
('trati', 'trat'),
('trene', 're''e ren tren'),
('tricu', 'ric tric'),
('trina', 'tri trin'),
('trixe', 'rix ti''e trix'),
('troci', 'toc toi troc'),
('tsaba', 'tsab'),
('tsali', 'tsa tsal'),
('tsani', 'tan tsan'),
('tsapi', 'tsap'),
('tsiju', 'tsi tsij'),
('tsina', 'sin tsin'),
('tsuku', 'tsuk'),
('tu', 'tuf'),
('tubnu', 'tu''u tubn'),
('tubra', 'tubr'),
('tugni', 'tu''i tug tugn'),
('tujli', 'tuj tujl'),
('tumla', 'tu''a tum tuml'),
('tunba', 'tub tunb'),
('tunka', 'tuk tunk'),
('tunlo', 'tu''o tul tunl'),
('tunta', 'tun tunt'),
('tuple', 'tu''e tup tupl'),
('turko', 'turk'),
('turni', 'tru turn'),
('tutci', 'tci tutc'),
('tutle', 'tutl'),
('tutra', 'tut tutr'),
('va', 'vaz'),
('vacri', 'vacr var'),
('vajni', 'vai vaj vajn'),
('valsi', 'val vals vla'),
('vamji', 'va''i vam vamj'),
('vamtu', 'vamt vat'),
('vanbi', 'vab vanb'),
('vanci', 'vac vanc'),
('vanju', 'van vanj'),
('vasru', 'vas vasr vau'),
('vasxu', 'va''u vasx vax'),
('ve', 'vel'),
('ve''e', 've''e'),
('vecnu', 've''u vecn ven'),
('vedli', 'vedl'),
('venfu', 'vef venf'),
('vensa', 'vens ves'),
('vente', 'vent'),
('vepre', 'vepr'),
('verba', 've''a ver verb'),
('vi', 'viz'),
('vibna', 'vib vibn'),
('vidni', 'vidn'),
('vidru', 'vidr vir'),
('vifne', 'vif vifn'),
('vikmi', 'vi''i vikm vim'),
('viknu', 'vik vikn'),
('vimcu', 'vi''u vic vimc'),
('vindu', 'vid vind'),
('vinji', 'vij vinj'),
('vinta', 'vint'),
('vipsi', 'vip vips'),
('virnu', 'virn vri'),
('viska', 'vi''a vis visk'),
('vitci', 'vit vitc'),
('vitke', 'vi''e vitk'),
('vitno', 'vi''o vitn'),
('vlagi', 'lag vlag'),
('vlile', 'vil vlil'),
('vlina', 'vlin'),
('vlipa', 'vli vlip'),
('vo', 'von'),
('vofli', 'vofl voi vol'),
('voksa', 'vo''a vok voks'),
('volve', 'volv'),
('vorme', 'vor vorm vro'),
('vraga', 'vra vrag'),
('vreji', 'rej vei vrej'),
('vreta', 'vre vret'),
('vrici', 'vric'),
('vrude', 'vrud vu''e vud'),
('vrusi', 'vrus vu''i vus'),
('vu', 'vuz'),
('vubla', 'vubl'),
('vujnu', 'vujn'),
('vukna', 'vukn'),
('vukro', 'vu''o vukr vur'),
('xa', 'xav'),
('xabju', 'xa''u xabj'),
('xadba', 'xab xadb'),
('xadji', 'xadj'),
('xadni', 'xad xadn'),
('xagji', 'xagj'),
('xagri', 'xagr'),
('xajmi', 'xajm xam'),
('xaksu', 'xak xaks'),
('xalbo', 'xalb'),
('xalka', 'xal xalk'),
('xalni', 'xaln'),
('xamgu', 'xag xamg xau'),
('xampo', 'xa''o xamp xap'),
('xamsi', 'xams xas'),
('xance', 'xa''e xan xanc'),
('xango', 'xang'),
('xanka', 'xank'),
('xanri', 'xanr xar'),
('xansa', 'xans'),
('xanto', 'xant'),
('xarci', 'xa''i xac xarc'),
('xarju', 'xaj xarj'),
('xarnu', 'xarn'),
('xasli', 'xasl'),
('xasne', 'xasn'),
('xatra', 'xa''a xatr'),
('xatsi', 'xat xats'),
('xazdo', 'xaz xazd zdo'),
('xe', 'xel'),
('xebni', 'xebn xei xen'),
('xebro', 'bro xeb xebr'),
('xecto', 'cto xect xet'),
('xedja', 'xe''a xedj xej'),
('xekri', 'xe''i xek xekr'),
('xelso', 'xels xes'),
('xendo', 'xe''o xed xend'),
('xenru', 'xe''u xenr xer'),
('xexso', 'xex xexs'),
('xigzo', 'xigz'),
('xindo', 'xin xind'),
('xinmo', 'xim xinm'),
('xirma', 'xi''a xir xirm'),
('xislu', 'xi''u xil xisl'),
('xispo', 'xip xisp'),
('xlali', 'xla xlal'),
('xlura', 'xlu xlur'),
('xorbo', 'xorb'),
('xorlo', 'xorl'),
('xotli', 'xoi xol xotl'),
('xrabo', 'rab xrab'),
('xrani', 'xai xran'),
('xriso', 'xi''o xis xris'),
('xrotu', 'xrot'),
('xruba', 'xrub xub'),
('xruki', 'xruk xuk'),
('xrula', 'rul xrul'),
('xruti', 'xru xrut'),
('xukmi', 'xu''i xukm xum'),
('xulta', 'xult'),
('xunre', 'xu''e xun xunr'),
('xurdo', 'xu''o xur xurd'),
('xusra', 'xu''a xus xusr'),
('xutla', 'xul xutl'),
('za''i', 'zaz'),
('za''o', 'za''o'),
('zabna', 'za''a zabn zan'),
('zajba', 'zaj zajb'),
('zalvi', 'zal zalv'),
('zanru', 'zanr zar zau'),
('zarci', 'zac zai zarc'),
('zargu', 'za''u zag zarg'),
('zasni', 'zas zasn'),
('zasti', 'za''i zast zat'),
('zbabu', 'bab zbab'),
('zbani', 'zban'),
('zbasu', 'zba zbas'),
('zbepi', 'zbe zbep'),
('zdani', 'zda zdan'),
('zdile', 'zdi zdil'),
('ze', 'zel'),
('ze''e', 'ze''e'),
('ze''o', 'ze''o zev'),
('zekri', 'zei zekr zer'),
('zenba', 'ze''a zen zenb'),
('zepti', 'zep zept'),
('zetro', 'zet zetr'),
('zevla', 'zevl'),
('zgadi', 'zgad'),
('zgana', 'zga zgan'),
('zgike', 'gi''e zgi zgik'),
('zi''o', 'zil'),
('zifre', 'zi''e zif zifr'),
('zinki', 'zi''i zin zink'),
('zirpu', 'zi''u zir zirp'),
('zivle', 'vle ziv zivl'),
('zmadu', 'mau zma zmad'),
('zmiku', 'zmi zmik'),
('zo''a', 'zo''a zon'),
('zo''i', 'zo''i zor'),
('zu''o', 'zum'),
('zucna', 'zucn'),
('zukte', 'zu''e zuk zukt'),
('zumri', 'zmu zumr'),
('zungi', 'zug zung'),
('zunle', 'zul zunl'),
('zunti', 'zu''i zun zunt'),
('zutse', 'tse zut zuts'),
('zvati', 'zva zvat');

-- Preserve displaced nonbaseline tokens. Prefer the community definition whose
-- notes actually mention the token; otherwise use the earliest community entry.
-- If only officialdata definitions exist, retain the note-derived proposal on
-- that definition, never in the official word-level list.
WITH displaced AS (
    SELECT v.valsiid, token
    FROM valsi v
    LEFT JOIN official_rafsi_baseline b ON b.word = v.word
    CROSS JOIN LATERAL regexp_split_to_table(trim(v.rafsi), '\s+') token
    WHERE v.source_langid = 1 AND v.typeid IN (1, 2) AND token <> ''
      AND NOT (token = ANY(regexp_split_to_array(COALESCE(b.rafsi, ''), '\s+')))
), attributed AS (
    SELECT chosen.definitionid, string_agg(DISTINCT token, ' ' ORDER BY token) AS rafsi
    FROM displaced x
    CROSS JOIN LATERAL (
        SELECT d.definitionid FROM definitions d JOIN users u ON u.userid = d.userid
        WHERE d.valsiid = x.valsiid
        ORDER BY (u.username != 'officialdata') DESC,
                 (position(x.token in COALESCE(d.notes, '')) > 0) DESC, d.definitionid
        LIMIT 1
    ) chosen
    GROUP BY chosen.definitionid
)
UPDATE definitions d SET rafsi = concat_ws(' ', NULLIF(d.rafsi, ''), a.rafsi)
FROM attributed a WHERE d.definitionid = a.definitionid;

UPDATE valsi v SET rafsi = NULLIF(b.rafsi, '')
FROM official_rafsi_baseline b
WHERE v.word = b.word AND v.source_langid = 1 AND v.typeid IN (1, 2);
UPDATE valsi v SET rafsi = NULL
WHERE v.source_langid = 1 AND v.typeid IN (1, 2)
  AND NOT EXISTS (SELECT 1 FROM official_rafsi_baseline b WHERE b.word = v.word);

-- Cache provenance for the join-free dictionary search.
ALTER TABLE definitions ADD COLUMN cached_official_rafsi TEXT;
CREATE OR REPLACE FUNCTION combined_rafsi(official TEXT, experimental TEXT)
RETURNS TEXT LANGUAGE SQL IMMUTABLE AS $$
    SELECT string_agg(token, ' ' ORDER BY token)
    FROM (SELECT DISTINCT token FROM regexp_split_to_table(concat_ws(' ', official, experimental), '\s+') token
          WHERE token <> '') tokens;
$$;

CREATE OR REPLACE FUNCTION sync_definition_cache_fields()
RETURNS TRIGGER AS $$
DECLARE
    target_definitionid INTEGER;
    target_valsiid INTEGER;
    target_natlangwordid INTEGER;
    kw_gloss TEXT := '';
    kw_text TEXT := '';
    v_word TEXT;
    v_rafsi TEXT;
    d_rafsi TEXT;
    v_cached_decomposition TEXT;
    v_canonical_word TEXT;
    v_source_langid INTEGER;
    v_typeid INTEGER;
    v_type_name TEXT;
    u_username TEXT;
    l_realname TEXT;
    d_definition TEXT;
    d_notes TEXT;
    d_selmaho TEXT;
BEGIN
    IF TG_TABLE_NAME = 'definitions' THEN
        target_definitionid := COALESCE(NEW.definitionid, OLD.definitionid);
        target_valsiid := COALESCE(NEW.valsiid, OLD.valsiid);
    ELSIF TG_TABLE_NAME = 'keywordmapping' THEN
        target_definitionid := COALESCE(NEW.definitionid, OLD.definitionid);
    ELSIF TG_TABLE_NAME = 'valsi' THEN
        target_valsiid := COALESCE(NEW.valsiid, OLD.valsiid);
    ELSIF TG_TABLE_NAME = 'natlangwords' THEN
        target_natlangwordid := COALESCE(NEW.wordid, OLD.wordid);
    END IF;

    IF target_definitionid IS NOT NULL THEN
        SELECT COALESCE(string_agg(LOWER(n.word), '|' ORDER BY n.word) FILTER (WHERE k.place = 0), ''),
               COALESCE(string_agg(LOWER(n.word || ' ' || COALESCE(n.meaning, '')), ' '), '')
        INTO kw_gloss, kw_text
        FROM keywordmapping k
        JOIN natlangwords n ON k.natlangwordid = n.wordid
        WHERE k.definitionid = target_definitionid;
    END IF;

    IF TG_TABLE_NAME = 'definitions' THEN
        SELECT d.definition, d.notes, d.selmaho, d.rafsi,
               v.word, v.rafsi, v.cached_decomposition, v.canonical_word, v.source_langid, v.typeid,
               vt.descriptor, u.username, l.realname
        INTO d_definition, d_notes, d_selmaho, d_rafsi,
             v_word, v_rafsi, v_cached_decomposition, v_canonical_word, v_source_langid, v_typeid,
             v_type_name, u_username, l_realname
        FROM definitions d
        JOIN valsi v ON d.valsiid = v.valsiid
        JOIN users u ON d.userid = u.userid
        JOIN languages l ON d.langid = l.langid
        JOIN valsitypes vt ON v.typeid = vt.typeid
        WHERE d.definitionid = target_definitionid;

        UPDATE definitions
        SET
            cached_username = u_username,
            cached_langrealname = l_realname,
            cached_type_name = v_type_name,
            cached_valsiword = v_word,
            cached_rafsi = combined_rafsi(v_rafsi, d_rafsi),
            cached_official_rafsi = v_rafsi,
            cached_decomposition = v_cached_decomposition,
            cached_canonical_word = v_canonical_word,
            cached_source_langid = v_source_langid,
            cached_typeid = v_typeid,
            cached_glosswords = kw_gloss,
            cached_search_text = LOWER(
                COALESCE(v_word, '') || ' ' ||
                COALESCE(combined_rafsi(v_rafsi, d_rafsi), '') || ' ' ||
                COALESCE(d_definition, '') || ' ' ||
                COALESCE(d_notes, '') || ' ' ||
                COALESCE(d_selmaho, '') || ' ' ||
                COALESCE(kw_text, '')
            )
        WHERE definitionid = target_definitionid;

    ELSIF TG_TABLE_NAME = 'keywordmapping' THEN
        UPDATE definitions d
        SET
            cached_glosswords = kw_gloss,
            cached_search_text = LOWER(
                COALESCE(d.cached_valsiword, '') || ' ' ||
                COALESCE(d.cached_rafsi, '') || ' ' ||
                COALESCE(d.definition, '') || ' ' ||
                COALESCE(d.notes, '') || ' ' ||
                COALESCE(d.selmaho, '') || ' ' ||
                COALESCE(kw_text, '')
            ),
            embedding = NULL
        WHERE d.definitionid = target_definitionid;

    ELSIF TG_TABLE_NAME = 'valsi' THEN
        WITH def_ids AS (
            SELECT definitionid FROM definitions WHERE valsiid = target_valsiid
        ),
        valsi_data AS (
            SELECT v.word, v.rafsi, v.cached_decomposition, v.canonical_word,
                   v.source_langid, v.typeid, vt.descriptor
            FROM valsi v
            JOIN valsitypes vt ON v.typeid = vt.typeid
            WHERE v.valsiid = target_valsiid
        ),
        keyword_agg AS (
            SELECT k.definitionid,
                   string_agg(LOWER(n.word), '|' ORDER BY n.word) FILTER (WHERE k.place = 0) AS glosswords,
                   string_agg(LOWER(n.word || ' ' || COALESCE(n.meaning, '')), ' ') AS keyword_text
            FROM keywordmapping k
            JOIN natlangwords n ON k.natlangwordid = n.wordid
            JOIN definitions d2 ON d2.definitionid = k.definitionid
            WHERE d2.valsiid = target_valsiid
            GROUP BY k.definitionid
        )
        UPDATE definitions
        SET
            cached_valsiword = vd.word,
            cached_rafsi = combined_rafsi(vd.rafsi, definitions.rafsi),
            cached_official_rafsi = vd.rafsi,
            cached_decomposition = vd.cached_decomposition,
            cached_canonical_word = vd.canonical_word,
            cached_source_langid = vd.source_langid,
            cached_typeid = vd.typeid,
            cached_type_name = vd.descriptor,
            cached_glosswords = COALESCE(ka.glosswords, ''),
            cached_search_text = LOWER(
                COALESCE(vd.word, '') || ' ' ||
                COALESCE(combined_rafsi(vd.rafsi, definitions.rafsi), '') || ' ' ||
                COALESCE(definitions.definition, '') || ' ' ||
                COALESCE(definitions.notes, '') || ' ' ||
                COALESCE(definitions.selmaho, '') || ' ' ||
                COALESCE(ka.keyword_text, '')
            )
        FROM def_ids
        CROSS JOIN valsi_data vd
        LEFT JOIN keyword_agg ka ON ka.definitionid = def_ids.definitionid
        WHERE definitions.definitionid = def_ids.definitionid;

    ELSIF TG_TABLE_NAME = 'users' THEN
        UPDATE definitions d
        SET cached_username = NEW.username
        WHERE d.userid = NEW.userid;

    ELSIF TG_TABLE_NAME = 'languages' THEN
        UPDATE definitions d
        SET cached_langrealname = NEW.realname
        WHERE d.langid = NEW.langid;

    ELSIF TG_TABLE_NAME = 'valsitypes' THEN
        UPDATE definitions d
        SET
            cached_type_name = NEW.descriptor,
            cached_typeid = NEW.typeid
        WHERE d.cached_typeid = NEW.typeid;

    ELSIF TG_TABLE_NAME = 'natlangwords' THEN
        WITH affected AS (
            SELECT DISTINCT k.definitionid
            FROM keywordmapping k
            WHERE k.natlangwordid = target_natlangwordid
        ),
        keyword_agg AS (
            SELECT k.definitionid,
                   MAX(d2.cached_valsiword) AS cached_valsiword,
                   MAX(d2.cached_rafsi) AS cached_rafsi,
                   MAX(d2.definition) AS def_text,
                   MAX(d2.notes) AS notes_text,
                   MAX(d2.selmaho) AS selmaho_text,
                   string_agg(LOWER(n.word), '|' ORDER BY n.word) FILTER (WHERE k.place = 0) AS glosswords,
                   string_agg(LOWER(n.word || ' ' || COALESCE(n.meaning, '')), ' ') AS keyword_text
            FROM keywordmapping k
            JOIN natlangwords n ON k.natlangwordid = n.wordid
            JOIN definitions d2 ON d2.definitionid = k.definitionid
            JOIN affected a ON a.definitionid = k.definitionid
            GROUP BY k.definitionid
        )
        UPDATE definitions
        SET
            cached_glosswords = COALESCE(ka.glosswords, ''),
            cached_search_text = LOWER(
                COALESCE(ka.cached_valsiword, '') || ' ' ||
                COALESCE(ka.cached_rafsi, '') || ' ' ||
                COALESCE(ka.def_text, '') || ' ' ||
                COALESCE(ka.notes_text, '') || ' ' ||
                COALESCE(ka.selmaho_text, '') || ' ' ||
                COALESCE(ka.keyword_text, '')
            ),
            embedding = NULL
        FROM affected
        LEFT JOIN keyword_agg ka ON ka.definitionid = affected.definitionid
        WHERE definitions.definitionid = affected.definitionid;
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION refresh_definition_cached_valsi(p_definitionid INTEGER)
RETURNS VOID AS $$
DECLARE
    v_word TEXT;
    v_rafsi TEXT;
    v_source_langid INTEGER;
    v_typeid SMALLINT;
    v_type_name TEXT;
    v_cached_decomposition TEXT;
    v_canonical_word TEXT;
    d_definition TEXT;
    d_notes TEXT;
    d_selmaho TEXT;
    d_rafsi TEXT;
    u_username TEXT;
    l_realname TEXT;
    kw_gloss TEXT;
    kw_text TEXT;
BEGIN
    SELECT COALESCE(string_agg(LOWER(n.word), '|' ORDER BY n.word) FILTER (WHERE k.place = 0), ''),
           COALESCE(string_agg(LOWER(n.word || ' ' || COALESCE(n.meaning, '')), ' '), '')
    INTO kw_gloss, kw_text
    FROM keywordmapping k
    JOIN natlangwords n ON k.natlangwordid = n.wordid
    WHERE k.definitionid = p_definitionid;

    SELECT d.definition, d.notes, d.selmaho, d.rafsi,
           v.word, v.rafsi, v.cached_decomposition, v.canonical_word, v.source_langid, v.typeid,
           vt.descriptor, u.username, l.realname
    INTO d_definition, d_notes, d_selmaho, d_rafsi,
         v_word, v_rafsi, v_cached_decomposition, v_canonical_word, v_source_langid, v_typeid,
         v_type_name, u_username, l_realname
    FROM definitions d
    JOIN valsi v ON d.valsiid = v.valsiid
    JOIN users u ON d.userid = u.userid
    JOIN languages l ON d.langid = l.langid
    JOIN valsitypes vt ON v.typeid = vt.typeid
    WHERE d.definitionid = p_definitionid;

    IF NOT FOUND THEN
        RETURN;
    END IF;

    UPDATE definitions
    SET
        cached_username = u_username,
        cached_langrealname = l_realname,
        cached_type_name = v_type_name,
        cached_valsiword = v_word,
        cached_rafsi = combined_rafsi(v_rafsi, d_rafsi),
        cached_official_rafsi = v_rafsi,
        cached_decomposition = v_cached_decomposition,
        cached_canonical_word = v_canonical_word,
        cached_source_langid = v_source_langid,
        cached_typeid = v_typeid,
        cached_glosswords = kw_gloss,
        cached_search_text = LOWER(
            COALESCE(v_word, '') || ' ' ||
            COALESCE(combined_rafsi(v_rafsi, d_rafsi), '') || ' ' ||
            COALESCE(d_definition, '') || ' ' ||
            COALESCE(d_notes, '') || ' ' ||
            COALESCE(d_selmaho, '') || ' ' ||
            COALESCE(kw_text, '')
        )
    WHERE definitionid = p_definitionid;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE VIEW convenientdefinitions AS
SELECT nd.definitionid,
    l.realname AS langrealname,
    l.tag,
    l.langid,
    v.valsiid,
    v.word,
    nd.definition,
    nd.notes,
    u.username,
    u.userid,
    nd."time",
    nd.definitionnum,
    v.rafsi AS rafsi,
    nd.selmaho,
    nd.jargon,
    v.rafsi AS official_rafsi,
    nd.rafsi AS experimental_rafsi
FROM public.definitions nd
JOIN public.languages l ON nd.langid = l.langid
JOIN public.valsi v ON nd.valsiid = v.valsiid
JOIN public.users u ON nd.userid = u.userid;

CREATE OR REPLACE FUNCTION editable_definition_rafsi(p_definitionid INTEGER)
RETURNS TEXT LANGUAGE SQL STABLE AS $$
    SELECT CASE WHEN u.username = 'officialdata' THEN v.rafsi ELSE d.rafsi END
    FROM definitions d JOIN users u ON u.userid = d.userid JOIN valsi v ON v.valsiid = d.valsiid
    WHERE d.definitionid = p_definitionid;
$$;

-- Old snapshots on officialdata definitions omitted the shared rafsi.
UPDATE definition_versions dv SET rafsi = v.rafsi
FROM definitions d JOIN users u ON u.userid = d.userid JOIN valsi v ON v.valsiid = d.valsiid
WHERE dv.definition_id = d.definitionid AND u.username = 'officialdata' AND dv.rafsi IS NULL;

-- Rafsi changes affect other words' decompositions. Invalidate the lujvo set
-- conservatively, including noncanonical entries so the existing worker rechecks.
CREATE OR REPLACE FUNCTION invalidate_rafsi_dependents()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF TG_TABLE_NAME = 'definitions' THEN
            IF OLD.rafsi IS NOT DISTINCT FROM NEW.rafsi AND OLD.valsiid = NEW.valsiid THEN RETURN NEW; END IF;
        ELSE
            IF OLD.rafsi IS NOT DISTINCT FROM NEW.rafsi AND OLD.word = NEW.word AND OLD.typeid = NEW.typeid AND OLD.source_langid IS NOT DISTINCT FROM NEW.source_langid THEN RETURN NEW; END IF;
            IF OLD.rafsi IS NOT DISTINCT FROM NEW.rafsi AND OLD.typeid NOT IN (1, 2, 7, 8) AND NEW.typeid NOT IN (1, 2, 7, 8) THEN RETURN NEW; END IF;
        END IF;
    ELSIF TG_OP = 'INSERT' THEN
        IF NEW.rafsi IS NULL THEN RETURN NEW; END IF;
    ELSE
        IF OLD.rafsi IS NULL THEN RETURN OLD; END IF;
    END IF;
    DELETE FROM cached_dictionary_exports;
    UPDATE valsi SET cached_decomposition = NULL, canonical_word = NULL,
                     related_expansion_key = NULL, trivial_se_checked = FALSE,
                     typeid = CASE WHEN typeid = 17 THEN 4 ELSE typeid END
    WHERE source_langid = 1 AND typeid IN (4, 17)
      AND (cached_decomposition IS NOT NULL OR canonical_word IS NOT NULL OR trivial_se_checked OR typeid = 17);
    RETURN COALESCE(NEW, OLD);
END;
$$;
CREATE TRIGGER trigger_rafsi_dependents_valsi
AFTER INSERT OR DELETE OR UPDATE OF rafsi, word, typeid, source_langid ON valsi
FOR EACH ROW EXECUTE FUNCTION invalidate_rafsi_dependents();
CREATE TRIGGER trigger_rafsi_dependents_definition
AFTER INSERT OR DELETE OR UPDATE OF rafsi, valsiid ON definitions
FOR EACH ROW EXECUTE FUNCTION invalidate_rafsi_dependents();

-- Initial invalidation and refresh after the baseline repair.
UPDATE valsi SET cached_decomposition = NULL, canonical_word = NULL,
                 related_expansion_key = NULL, trivial_se_checked = FALSE,
                 typeid = CASE WHEN typeid = 17 THEN 4 ELSE typeid END
WHERE source_langid = 1 AND typeid IN (4, 17);
UPDATE definitions SET rafsi = rafsi;

-- Cached exports must not continue serving displaced assignments.
DELETE FROM cached_dictionary_exports;
