/** Fallback titles for pages excluded from search results. */
export const routeTitles: Record<string, string> = {
  Tiktoknu: 'Lojban Learning Feed',
  Signup: 'Create an Account',
  Login: 'Sign In',
  Me: 'My Profile',
  AddDefinition: 'Add a Dictionary Entry',
  UpsertDefinitionMarkdownNew: 'Create a Markdown Definition',
  UpsertDefinitionMarkdownEdit: 'Edit a Markdown Definition',
  EditDefinition: 'Edit a Dictionary Definition',
  ResetPassword: 'Reset Password',
  UpsertWiki: 'Create a Wiki Article',
  WikiById: 'Wiki Article',
  EditWiki: 'Edit a Wiki Article',
  NewThread: 'Start a Discussion',
  VersionHistory: 'Definition Version History',
  UserProfile: 'Contributor Profile',
  UserList: 'Contributors',
  LanguageProfile: 'Language Profile',
  DictionaryExport: 'Export the Dictionary',
  SearchExport: 'Export Search Results',
  CachedExports: 'Prepared Dictionary Exports',
  Library: 'My Library',
  UserActivity: 'Contributor Activity',
  ConfirmEmail: 'Confirm Email',
  CollectionTiktoknu: 'Collection Learning Feed',
  FlashcardStudy: 'Study Flashcards',
  LingoStudy: 'Lojban Lesson',
  CollectionCustomTextBulk: 'Edit Collection Text',
  LingoLearn: 'Learn Lojban',
  LingoLogin: 'Sign In to Lingo',
  LingoSignup: 'Join Lingo',
  ChangePassword: 'Change Password',
  PaypalReturn: 'Payment Result',
  Balance: 'Account Balance',
  BulkImport: 'Bulk Import Definitions',
  BulkImportClients: 'Bulk Import Clients',
  AssistantChat: 'Lojban Assistant',
  Messages: 'Private Messages',
  Chat: 'Private Conversation',
  NewChat: 'New Conversation',
  VideoCall: 'Video Call',
  NotFound: 'Page Not Found',
  OAuthCallback: 'Completing Sign In',
}

/** Existing translations for private route titles. */
export const routeTitleKeys: Record<string, string> = {
  Signup: 'signup.title',
  Login: 'login.title',
  NewThread: 'newThreadPage.pageTitle',
  DictionaryExport: 'dictionaryExport.title',
  SearchExport: 'searchExport.title',
  Library: 'nav.library',
  LingoLearn: 'lingo.learn',
  AssistantChat: 'assistantChat.title',
  NotFound: 'notFoundPage.pageTitle',
}

/** Existing translations for private route descriptions. */
export const routeDescriptionKeys: Record<string, string> = {
  NotFound: 'notFoundPage.description',
}

/** Fallback descriptions for pages excluded from search results. */
export const routeDescriptions: Record<string, string> = {
  Tiktoknu: 'Explore Lojban vocabulary in a short-form learning feed.',
  Signup: 'Create an account to contribute definitions, save collections, and learn Lojban.',
  Login: 'Sign in to your Lojban Portal account to continue learning and contributing.',
  Me: 'Manage your Lojban profile, activity, bookmarks, and account settings.',
  AddDefinition: 'Add a Lojban dictionary entry and share its meaning with the community.',
  UpsertDefinitionMarkdownNew: 'Create a Lojban definition using Markdown.',
  UpsertDefinitionMarkdownEdit: 'Edit a Lojban definition using Markdown.',
  EditDefinition: 'Edit a Lojban dictionary definition.',
  ResetPassword: 'Reset your Lojban Portal password securely.',
  UpsertWiki: 'Create a Lojban wiki article.',
  WikiById: 'Open a Lojban wiki article.',
  EditWiki: 'Edit a Lojban wiki article.',
  NewThread: 'Start a new discussion with the Lojban community.',
  VersionHistory: 'Review past versions and edits of a Lojban definition.',
  UserProfile: 'View a contributor profile and their activity in the Lojban community.',
  UserList: 'Browse contributors to the Lojban dictionary and community.',
  LanguageProfile: 'Explore dictionary content and translation activity for a language.',
  DictionaryExport: 'Download Lojban dictionary data in your chosen language and format.',
  SearchExport: 'Export filtered Lojban dictionary search results in your preferred format.',
  CachedExports: 'Download prepared exports of Lojban dictionary data.',
  Library: 'Find and manage your saved Lojban collections and study materials.',
  UserActivity: 'See a contributor’s edits and activity in the Lojban community.',
  ConfirmEmail: 'Confirm your email address for your Lojban Portal account.',
  CollectionTiktoknu: 'Practice words from a Lojban collection in a short-form learning feed.',
  FlashcardStudy: 'Study Lojban vocabulary with interactive flashcards.',
  LingoStudy: 'Practice Lojban words and phrases in an interactive lesson.',
  CollectionCustomTextBulk: 'Edit custom text for items in a Lojban collection.',
  LingoLearn: 'Continue your Lojban lessons and vocabulary practice.',
  LingoLogin: 'Sign in to continue your Lojban learning progress.',
  LingoSignup: 'Create an account to save your Lojban learning progress.',
  ChangePassword: 'Change the password for your Lojban Portal account.',
  PaypalReturn: 'Review the result of your Lojban Portal payment.',
  Balance: 'View and manage your Lojban Portal balance.',
  BulkImport: 'Import Lojban dictionary definitions in bulk.',
  BulkImportClients: 'Manage clients for bulk Lojban dictionary imports.',
  AssistantChat: 'Ask the Lojban assistant about words, grammar, and usage.',
  Messages: 'View your private conversations with other Lojban Portal users.',
  Chat: 'Read and reply to a private Lojban Portal conversation.',
  NewChat: 'Start a private conversation with another Lojban Portal user.',
  VideoCall: 'Join a private Lojban Portal video call.',
  NotFound: 'The requested page could not be found in the Lojban Portal.',
  OAuthCallback: 'Complete sign-in to your Lojban Portal account.',
}

/** Personal, transactional, and editing pages should stay out of search results. */
export const noindexRoutes = new Set([
  'Signup',
  'Login',
  'Me',
  'AddDefinition',
  'UpsertDefinitionMarkdownNew',
  'UpsertDefinitionMarkdownEdit',
  'EditDefinition',
  'ResetPassword',
  'UpsertWiki',
  'WikiById',
  'EditWiki',
  'NewThread',
  'VersionHistory',
  'UserProfile',
  'UserActivity',
  'UserList',
  'LanguageProfile',
  'DictionaryExport',
  'SearchExport',
  'CachedExports',
  'Library',
  'ConfirmEmail',
  'FlashcardStudy',
  'LingoStudy',
  'CollectionCustomTextBulk',
  'LingoLearn',
  'LingoLogin',
  'LingoSignup',
  'ChangePassword',
  'PaypalReturn',
  'Balance',
  'BulkImport',
  'BulkImportClients',
  'AssistantChat',
  'Messages',
  'Chat',
  'NewChat',
  'VideoCall',
  'NotFound',
  'OAuthCallback',
  'Tiktoknu',
  'CollectionTiktoknu',
])
